### ISSUE TITLE
[BUG] installation in debian 10 with ansible 2.14.1 (2022-12) fails - observations

### ISSUE THREAD

**Issue by ksbbf** [eXist-db/existdb-ansible-role#50]
Dear all, 

I started recently (dec. 2022) with ansible (2.14.1) and tried to install exist-db 5.4.1 on a debian 10 server (which is the most recent debian version for the vm, not 11). 
- I use vscode with extensions for ansible; syntax checks asf. are enabled. 
- I tried to do a remote_install with exist.db 5.4.1 (exist-distribution-5.4.1-unix.tar.bz2) 

These are the main obstacles on my way:
- when I used a playbook - like the example in the readme - where the role is executed as a tasks, ansible did something, but didn't process the whole installation. The installation was quite complete, when I called the role directly like

```
  name: My exist installation
  hosts: existserver
  roles:
    - role: existdb-ansible-role
      vars:
        exist_instname: 'existdb'
        exist_instuser: existdb
        ...
```
It seems, there is a difference how ansible processes the role meanwhile.
- Similarly, ansible doesn't like _warn: no_ in a task with shell-commands. This raises fatal errors and the execution stops completely.   _warn: no_ is used at several occasions. - I commented them out.
- The task _existdb : Backup installed exist instance_ didn't work in my case, and even the variable _exist_backup_previnstall: no_ is without effect. - I silenced this task by a comment.
- The variable _exist_instdns_ (for a domain name) mentioned in the README-example doesn't appear in the code.
- At the end, jetty could not start because a file - in fact all jetty configuration - _INSTALLDIR/etc/jetty/jetty-plus.xml_ is missing.

maybe somebody finds these notes helpfully. I'll came back to them later.
regards
